/********************************************************************/
/****************Insertar Pais**************************************/
/*******************************************************************/
INSERT INTO ebja.pais (id, nombre, estado) VALUES (102, 'AUSTRIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (103, 'BELGICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (104, 'BULGARIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (106, 'CHIPRE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (107, 'DINAMARCA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (108, 'ESPAÑA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (109, 'FINLANDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (110, 'FRANCIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (111, 'GRECIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (112, 'HUNGRIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (113, 'IRLANDA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (115, 'ITALIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (117, 'LUXEMBURGO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (118, 'MALTA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (121, 'PAISES BAJOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (122, 'POLONIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (123, 'PORTUGAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (125, 'REINO UNIDO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (126, 'ALEMANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (128, 'RUMANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (131, 'SUECIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (136, 'LETONIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (141, 'ESTONIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (142, 'LITUANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (143, 'REPUBLICA CHECA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (144, 'REPUBLICA ESLOVACA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (147, 'ESLOVENIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (198, 'OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (101, 'ALBANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (114, 'ISLANDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (116, 'LIECHTENSTEIN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (119, 'MONACO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (120, 'NORUEGA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (124, 'ANDORRA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (129, 'SAN MARINO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (130, 'SANTA SEDE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (132, 'SUIZA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (135, 'UCRANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (137, 'MOLDAVIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (138, 'BELARUS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (139, 'GEORGIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (145, 'BOSNIA Y HERZEGOVINA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (146, 'CROACIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (148, 'ARMENIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (154, 'RUSIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (156, 'MACEDONIA ', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (157, 'SERBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (158, 'MONTENEGRO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (170, 'GUERNESEY', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (171, 'SVALBARD Y JAN MAYEN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (172, 'ISLAS FEROE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (173, 'ISLA DE MAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (174, 'GIBRALTAR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (175, 'ISLAS DEL CANAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (176, 'JERSEY', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (177, 'ISLAS ALAND', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (436, 'TURQUIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (199, 'OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (201, 'BURKINA FASO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (202, 'ANGOLA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (203, 'ARGELIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (204, 'BENIN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (205, 'BOTSWANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (206, 'BURUNDI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (207, 'CABO VERDE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (208, 'CAMERUN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (209, 'COMORES', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (210, 'CONGO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (211, 'COSTA DE MARFIL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (212, 'DJIBOUTI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (213, 'EGIPTO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (214, 'ETIOPIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (215, 'GABON', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (216, 'GAMBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (217, 'GHANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (218, 'GUINEA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (219, 'GUINEA-BISSAU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (220, 'GUINEA ECUATORIAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (221, 'KENIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (222, 'LESOTHO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (223, 'LIBERIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (224, 'LIBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (225, 'MADAGASCAR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (226, 'MALAWI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (227, 'MALI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (228, 'MARRUECOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (229, 'MAURICIO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (230, 'MAURITANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (231, 'MOZAMBIQUE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (232, 'NAMIBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (233, 'NIGER', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (234, 'NIGERIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (235, 'REPUBLICA CENTROAFRICANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (236, 'SUDAFRICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (237, 'RUANDA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (238, 'SANTO TOME Y PRINCIPE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (239, 'SENEGAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (240, 'SEYCHELLES', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (241, 'SIERRA LEONA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (242, 'SOMALIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (243, 'SUDAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (244, 'SWAZILANDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (245, 'TANZANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (246, 'CHAD', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (247, 'TOGO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (248, 'TUNEZ', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (249, 'UGANDA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (250, 'REP.DEMOCRATICA DEL CONGO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (251, 'ZAMBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (252, 'ZIMBABWE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (253, 'ERITREA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (260, 'SANTA HELENA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (261, 'REUNION', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (262, 'MAYOTTE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (263, 'SAHARA OCCIDENTAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (299, 'OTROS PAISES O TERRITORIOS DE AFRICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (301, 'CANADA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (302, 'ESTADOS UNIDOS DE AMERICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (303, 'MEXICO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (370, 'SAN PEDRO Y MIQUELON ', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (371, 'GROENLANDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (396, 'OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (310, 'ANTIGUA Y BARBUDA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (311, 'BAHAMAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (312, 'BARBADOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (313, 'BELICE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (314, 'COSTA RICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (315, 'CUBA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (316, 'DOMINICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (317, 'EL SALVADOR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (318, 'GRANADA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (319, 'GUATEMALA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (320, 'HAITI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (321, 'HONDURAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (322, 'JAMAICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (323, 'NICARAGUA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (324, 'PANAMA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (325, 'SAN VICENTE Y LAS GRANADINAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (326, 'REPUBLICA DOMINICANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (327, 'TRINIDAD Y TOBAGO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (328, 'SANTA LUCIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (329, 'SAN CRISTOBAL Y NIEVES', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (380, 'ISLAS CAIMÁN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (381, 'ISLAS TURCAS Y CAICOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (382, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (383, 'GUADALUPE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (384, 'ANTILLAS HOLANDESAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (385, 'SAN MARTIN (PARTE FRANCESA)', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (386, 'ARUBA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (387, 'MONTSERRAT', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (388, 'ANGUILLA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (389, 'SAN BARTOLOME', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (390, 'MARTINICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (391, 'PUERTO RICO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (392, 'BERMUDAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (393, 'ISLAS VIRGENES BRITANICAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (398, 'OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (340, 'ARGENTINA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (341, 'BOLIVIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (342, 'BRASIL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (343, 'COLOMBIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (344, 'CHILE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (345, 'ECUADOR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (346, 'GUYANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (347, 'PARAGUAY', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (348, 'PERU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (349, 'SURINAM', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (350, 'URUGUAY', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (351, 'VENEZUELA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (394, 'GUAYANA FRANCESA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (395, 'ISLAS MALVINAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (399, 'OTROS PAISES O TERRITORIOS  DE SUDAMERICA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (401, 'AFGANISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (402, 'ARABIA SAUDI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (403, 'BAHREIN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (404, 'BANGLADESH', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (405, 'MYANMAR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (407, 'CHINA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (408, 'EMIRATOS ARABES UNIDOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (409, 'FILIPINAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (410, 'INDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (411, 'INDONESIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (412, 'IRAQ', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (413, 'IRAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (414, 'ISRAEL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (415, 'JAPON', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (416, 'JORDANIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (417, 'CAMBOYA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (418, 'KUWAIT', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (419, 'LAOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (420, 'LIBANO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (421, 'MALASIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (422, 'MALDIVAS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (423, 'MONGOLIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (424, 'NEPAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (425, 'OMAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (426, 'PAKISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (427, 'QATAR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (430, 'COREA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (431, 'COREA DEL NORTE ', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (432, 'SINGAPUR', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (433, 'SIRIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (434, 'SRI LANKA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (435, 'TAILANDIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (437, 'VIETNAM', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (439, 'BRUNEI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (440, 'ISLAS MARSHALL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (441, 'YEMEN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (442, 'AZERBAIYAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (443, 'KAZAJSTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (444, 'KIRGUISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (445, 'TADYIKISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (446, 'TURKMENISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (447, 'UZBEKISTAN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (448, 'ISLAS MARIANAS DEL NORTE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (449, 'PALESTINA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (450, 'HONG KONG', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (453, 'BHUTÁN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (454, 'GUAM', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (455, 'MACAO', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (499, 'OTROS PAISES O TERRITORIOS DE ASIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (501, 'AUSTRALIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (502, 'FIJI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (504, 'NUEVA ZELANDA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (505, 'PAPUA NUEVA GUINEA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (506, 'ISLAS SALOMON', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (507, 'SAMOA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (508, 'TONGA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (509, 'VANUATU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (511, 'MICRONESIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (512, 'TUVALU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (513, 'ISLAS COOK', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (515, 'NAURU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (516, 'PALAOS', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (517, 'TIMOR ORIENTAL', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (520, 'POLINESIA FRANCESA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (521, 'ISLA NORFOLK', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (522, 'KIRIBATI', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (523, 'NIUE', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (524, 'ISLAS PITCAIRN', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (525, 'TOKELAU', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (526, 'NUEVA CALEDONIA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (527, 'WALLIS Y FORTUNA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (528, 'SAMOA AMERICANA', '1');
INSERT INTO ebja.pais (id, nombre, estado) VALUES (599, 'OTROS PAISES O TERRITORIOS DE OCEANIA', '1');

SELECT setval('ebja.pais_id_seq',(select max(id) from ebja.pais),'t');

/****************************************************************************/
/****************Insertar Tipo Programa**************************************/
/****************************************************************************/
INSERT INTO ebja.tipo_programa (id, nemonico, nombre, estado) VALUES (E'1', E'ME-TP-01', E'ALFABETIZACIÓN', E'1');
INSERT INTO ebja.tipo_programa (id, nemonico, nombre, estado) VALUES (E'2', E'ME-TP-02', E'EDUCACIÓN BÁSICA', E'1');
INSERT INTO ebja.tipo_programa (id, nemonico, nombre, estado) VALUES (E'3', E'ME-TP-03', E'BÁSICA SUPERIOR', E'1');
INSERT INTO ebja.tipo_programa (id, nemonico, nombre, estado) VALUES (E'4', E'ME-TP-04', E'BACHILLERATO', E'1');

SELECT setval('ebja.tipo_programa_id_seq',(select max(id) from ebja.tipo_programa),'t');

/************************************************************************/
/****************Insertar Modalidad**************************************/
/************************************************************************/
INSERT INTO ebja.modalidad (id, nemonico, nombre, estado) VALUES (E'1', E'MOD-01', E'PRESENCIAL', E'1');
INSERT INTO ebja.modalidad (id, nemonico, nombre, estado) VALUES (E'2', E'MOD-02', E'SEMIPRESENCIAL', E'1');
INSERT INTO ebja.modalidad (id, nemonico, nombre, estado) VALUES (E'3', E'MOD-03', E'DISTANCIA-VIRTUAL', E'1');

SELECT setval('ebja.modalidad_id_seq',(select max(id) from ebja.modalidad),'t');

/*******************************************************************/
/****************Insertar Fase**************************************/
/*******************************************************************/
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'1', DEFAULT, E'ME-FASE-01', E'INSCRIPCIÓN', DEFAULT, E'1', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'2', DEFAULT, E'ME-FASE-02', E'INSTITUCIONES', DEFAULT, E'2', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'3', DEFAULT, E'ME-FASE-03', E'DOCENTES', DEFAULT, E'3', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'4', E'1', E'ME-FASE-04', E'ASIGNACIÓN', DEFAULT, E'4', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'5', E'4', E'ME-FASE-05', E'RE-ASIGNACIÓN', DEFAULT, E'5', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'6', DEFAULT, E'ME-FASE-06', E'CONSULTA ASIGNAÓN', DEFAULT, E'6', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'7', DEFAULT, E'ME-FASE-07', E'REGISTRAR MATRICULA', DEFAULT, E'7', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'8', DEFAULT, E'ME-FASE-08', E'ACTIVAR MATRICULA', DEFAULT, E'8', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'9', E'7', E'ME-FASE-09', E'TRASLADO', DEFAULT, E'9', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'10', DEFAULT, E'ME-FASE-10', E'MALLA CURRICULAR', DEFAULT, E'10', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'11', DEFAULT, E'ME-FASE-11', E'CALIFICACIONES', DEFAULT, E'11', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'12', DEFAULT, E'ME-FASE-12', E'ASISTENCIA', DEFAULT, E'12', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'13', DEFAULT, E'ME-FASE-13', E'CERTIFICACIÓN - PROMOCIÓN', DEFAULT, E'13', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'14', DEFAULT, E'ME-FASE-14', E'TITULACIÓN', DEFAULT, E'14', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'15', DEFAULT, E'ME-FASE-15', E'SELECCIÓN DE ABANDERADOS', DEFAULT, E'15', E'1');
INSERT INTO ebja.fase (id, id_fase_padre, nemonico, nombre, observacion, orden, estado) VALUES (E'16', DEFAULT, E'ME-FASE-16', E'ACREDITACIÓN', DEFAULT, E'16', E'1');

SELECT setval('ebja.fase_id_seq',(select max(id) from ebja.fase),'t');


/******************************************************************/
/****************Insertar Formulario *******************************/
/*******************************************************************/
INSERT INTO ebja.formulario(id, id_fase, nombre, nemonico, observacion, estado) VALUES (E'1', E'1', 'Inscripción','INSC', 'Pantalla Inscripción',E'1');

SELECT setval('ebja.formulario_id_seq',(select max(id) from ebja.formulario),'t');



